version: "3.8"
services:
  #------------------------------------------------- Client App
  client:
    build: "./client/"
    ports:
      - 8080:8080
    container_name: "mediscreen-client"
    depends_on:
      - config-server
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- Config Server
  config-server:
    build: "./config-server/"
    ports:
      - 9101:9101
    container_name: "mediscreen-config-server"
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- Patient Microservices
  patient-ms:
    build: "./patient-ms/"
    ports:
      - 8082:8082
    container_name: "mediscreen-patient-ms"
    depends_on:
      - config-server
      - mongo
    command:
      "--spring.profiles.active=docker --spring.server.port=8082"
  #------------------------------------------------- Eureka EMS Server
  eureka-server:
    build: "./eureka-server/"
    ports:
      - 9111:9111
    container_name: "mediscreen-eureka-server"
    depends_on:
      - config-server
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- Zuul EMS Server
  zuul-server:
    build: "./zuul-server/"
    ports:
      - 9121:9121
    container_name: "mediscreen-zuul-server"
    depends_on:
      - config-server
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- MongoDB database
  mongo:
    image: mongo
    restart: always
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "toor"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db

  #------------------------------------------------- MongoDB GUI
  mongo-express:
    image: mongo-express
    restart: always
    container_name: "mongo-express"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "toor"