version: "3.8"
services:
  #------------------------------------------------- Client App
  client:
    build: "./client/"
    ports:
      - 8080:8080
    container_name: "mediscreen-client"
    depends_on:
      - config-server
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- Config Server
  config-server:
    build: "./config-server/"
    ports:
      - 9101:9101
    container_name: "mediscreen-config-server"
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- Patient Microservices
  patient-ms:
    build: "./patient-ms/"
    ports:
      - 8081:8081
    container_name: "mediscreen-patient-ms"
    depends_on:
      - config-server
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- Eureka EMS Server
  eureka-server:
    build: "./eureka-server/"
    ports:
      - 9111:9111
    container_name: "mediscreen-eureka-server"
    depends_on:
      - config-server
    command:
      "--spring.profiles.active=docker"
  #------------------------------------------------- Zuul EMS Server
  zuul-server:
    build: "./zuul-server/"
    ports:
      - 9121:9121
    container_name: "mediscreen-zuul-server"
    depends_on:
      - config-server
    command:
      "--spring.profiles.active=docker"